import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { AuthProvider } from "@/utils/AuthProvider";
import { dbConfig } from "@/utils/dbConfig";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConfig();
  return (
    // <AuthProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    // </AuthProvider>
  );
}
